# https://github.com/ludeeus/integration_blueprint/blob/main/.ruff.toml
# ---------------------------------------------------------------------
# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py313"

[lint]
select = [
    "ALL",
]

ignore = [
    "ANN401",
    "D203",
    "D212",
    "COM812",
    "ISC001",
    "TID252",
    "G004",
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25

[lint.per-file-ignores]
"tests/**" = [
    "ANN001",  # missing type annotation for function argument
    "ANN201",  # missing return type annotation for public function
    "ANN202",  # missing return type annotation for private function
    "DTZ001",  # datetime-without-timezone
    "S101",    # use of assert (expected in pytest)
    "SLF001",  # private member access (testing internals)
    "PLR2004", # magic values in comparisons
    "E501",    # Line too long
]
